[phases.setup]
nixPkgs = ["php85", "php85Extensions.pdo_mysql", "php85Extensions.mbstring", "php85Extensions.xml", "php85Extensions.curl", "php85Extensions.zip", "php85Extensions.gd", "php85Extensions.bcmath", "php85Extensions.tokenizer", "php85Extensions.openssl", "php85Extensions.sodium", "libpng", "libjpeg"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && vendor/bin/heroku-php-apache2 public/"